services:

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - 33060:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - task-network
    

  # Backend - FastAPI сервер
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-manager-backend
    ports:
      - "8000:8000"
    volumes:
      # Тома для сохранения данных
      - tasks-db-data:/db
      - ./db:/db
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - task-network
    restart: unless-stopped
    depends_on:
      - db

networks:
  task-network:
    driver: bridge

volumes:
  # task-data:
  #   driver: local

  tasks-db-data:
    driver: local